feat: Task 12.7 CSS Variables
Anisha-Alexander/html-css-tutorials pull request #7
Opened 2022-09-13 10:45 UTC by Anisha-Alexander

2022-09-13 10:53 UTC, donjude-eng requested changes

2022-09-13 10:53 UTC, donjude-eng commented on Tutorial12.6/css-grid-lines.html
> +        font-family: 'Nunito Semibold';
@Anisha-Alexander Why didn't we keep a separate CSS file?

2022-09-13 10:53 UTC, donjude-eng commented on Tutorial12.7/style.css
> +
remove this space

2022-09-13 10:53 UTC, donjude-eng commented on Tutorial12.7/swatches.js
> +
use const instead

2022-09-13 11:38 UTC, Anisha-Alexander commented on Tutorial12.6/css-grid-lines.html
> +        font-family: 'Nunito Semibold';
CSS files for each tutorial are almost the same so mainly to avoid confusion . And in the tutorial too they wrote CSS internally so I followed the same to avoid confusion.

2022-09-13 11:40 UTC, Anisha-Alexander commented on Tutorial12.7/style.css
> +
ok

2022-09-13 11:41 UTC, Anisha-Alexander commented on Tutorial12.7/swatches.js
> +
Din get u

2022-09-14 04:26 UTC, merged

2022-09-14 04:43 UTC, donjude-eng commented on Tutorial12.6/css-grid-lines.html
> +        font-family: 'Nunito Semibold';
ahh okay dot it